title: Steve Guntrip
email: mail@steveguntrip.co.uk
description: Steve Guntrip's blog and portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: guntrip
github_username:  stevecat
paginate: 5
paginate_path: "/page:num/"
permalink: "/:year/:month/:slug/"
break_at: 200 # how many words to break a post at

# Helpers
blog_images_path: "/assets/images/blog/"
photos_images_path: "/assets/images/photography/"
images_path: "/assets/images/"

# Build settings
markdown: kramdown

# Local settings
host: 0.0.0.0
